apiVersion: automation.cloudbees.io/v1alpha1
kind: action

name: hello-action
inputs:
  who-to-greet:
    description: 'Who to greet?'
    required: true
runs:
  using: composite
  steps:
    - id: action-step
      uses: docker://alpine:3.17
      shell: sh
      run: |
        echo "Hello from action ${{inputs.who-to-greet}}"
