apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Hello world custom platform action
        id: hello
        uses: mluzcabrera/customactionsmlcb/.cloudbees/actions/hello-world-action
        with:
           who-to-greet: 'Mariluz'
      - name: Print output from custom action
        id: print-output
        uses: docker://alpine:3.17
        shell: sh
        run: | 
          echo ${{ steps.hello.outputs.random-number }}
