apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  invokecustomcomposite:
    steps:
      - uses: mluzcabrera/customactionsmlcb/.cloudbees/actions/hello-world-action
        name: Hello world custom platform action
        id: hello
        with:
          who-to-greet: Mariluz
      - uses: docker://alpine:3.17
        name: Print output from custom action
        id: print-output
        shell: sh
        run: |
          echo ${{ steps.hello.outputs.random-number }}
  invokecustomjavascript:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"

