name: Use Hello World action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Hello world action step
      uses: ./.github/actions/hello-world-action
      with:
        who-to-greet: 'GitHub Actions'
